language: generic
sudo: false
before_install:
  - mkdir ~/.emacs.d
  - curl -O https://gist.githubusercontent.com/stakemori/a32d367baedd12b590888c6faceb28d9/raw/066838635c2b4ef11cacf1859d7089789d1a41f9/init.el
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
script:
  - emacs --version
  - make travis-test
