language: generic
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EMACS=emacs EVM_EMACS=emacs-24.4-bin
  - EMACS=emacs EVM_EMACS=emacs-24.5-bin
  - EMACS=emacs EVM_EMACS=emacs-25-pre
script:
  - emacs --version
  - make test

script:
  - emacs --version
  - make test
